# Configuración de DQN
env_name: "CartPole-v1"
input_shape: (4,)
num_actions: 2
environment:
  name: "CartPole-v1"
  max_episode_steps: 500
  # reward_threshold: 995
model:
  dense_layers: 
    - units: 128
      activation: "relu"
      kernel_initializer: "he_uniform"
    - units: 64
      activation: "relu"
      kernel_initializer: "he_uniform"
    - units: 62
      activation: "relu"
      kernel_initializer: "he_uniform"
replay-buffer:
  type: "standard"
  capacity: 2000
agent:
  episodes: 1000
  gamma: 0.95
  epsilon: 1.0
  epsilon-min: 0.001
  epsilon-decay: 0.999
  batch-size: 64
  train-start: 1000
